# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AddOp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='AddOp.proto',
  package='Ops',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0b\x41\x64\x64Op.proto\x12\x03Ops\x1a\x19google/protobuf/any.proto\"\xa5\x02\n\x05\x41\x64\x64Op\x12\"\n\x02id\x18\x01 \x01(\x0b\x32\x16.Ops.AddOp.VectorClock\x12!\n\x06opType\x18\x02 \x01(\x0e\x32\x11.Ops.AddOp.OpType\x12\r\n\x05\x66ield\x18\x03 \x01(\t\x12#\n\x05value\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x1a\x81\x01\n\x0bVectorClock\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x32\n\x06vector\x18\x02 \x03(\x0b\x32\".Ops.AddOp.VectorClock.VectorEntry\x1a-\n\x0bVectorEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x1d\n\x06OpType\x12\x07\n\x03\x41\x64\x64\x10\x00\x12\n\n\x06Remove\x10\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])



_ADDOP_OPTYPE = _descriptor.EnumDescriptor(
  name='OpType',
  full_name='Ops.AddOp.OpType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Add', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Remove', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=312,
  serialized_end=341,
)
_sym_db.RegisterEnumDescriptor(_ADDOP_OPTYPE)


_ADDOP_VECTORCLOCK_VECTORENTRY = _descriptor.Descriptor(
  name='VectorEntry',
  full_name='Ops.AddOp.VectorClock.VectorEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Ops.AddOp.VectorClock.VectorEntry.key', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Ops.AddOp.VectorClock.VectorEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=310,
)

_ADDOP_VECTORCLOCK = _descriptor.Descriptor(
  name='VectorClock',
  full_name='Ops.AddOp.VectorClock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='Ops.AddOp.VectorClock.user_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vector', full_name='Ops.AddOp.VectorClock.vector', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ADDOP_VECTORCLOCK_VECTORENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=310,
)

_ADDOP = _descriptor.Descriptor(
  name='AddOp',
  full_name='Ops.AddOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Ops.AddOp.id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opType', full_name='Ops.AddOp.opType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='field', full_name='Ops.AddOp.field', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Ops.AddOp.value', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ADDOP_VECTORCLOCK, ],
  enum_types=[
    _ADDOP_OPTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=341,
)

_ADDOP_VECTORCLOCK_VECTORENTRY.containing_type = _ADDOP_VECTORCLOCK
_ADDOP_VECTORCLOCK.fields_by_name['vector'].message_type = _ADDOP_VECTORCLOCK_VECTORENTRY
_ADDOP_VECTORCLOCK.containing_type = _ADDOP
_ADDOP.fields_by_name['id'].message_type = _ADDOP_VECTORCLOCK
_ADDOP.fields_by_name['opType'].enum_type = _ADDOP_OPTYPE
_ADDOP.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_ADDOP_OPTYPE.containing_type = _ADDOP
DESCRIPTOR.message_types_by_name['AddOp'] = _ADDOP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddOp = _reflection.GeneratedProtocolMessageType('AddOp', (_message.Message,), {

  'VectorClock' : _reflection.GeneratedProtocolMessageType('VectorClock', (_message.Message,), {

    'VectorEntry' : _reflection.GeneratedProtocolMessageType('VectorEntry', (_message.Message,), {
      'DESCRIPTOR' : _ADDOP_VECTORCLOCK_VECTORENTRY,
      '__module__' : 'AddOp_pb2'
      # @@protoc_insertion_point(class_scope:Ops.AddOp.VectorClock.VectorEntry)
      })
    ,
    'DESCRIPTOR' : _ADDOP_VECTORCLOCK,
    '__module__' : 'AddOp_pb2'
    # @@protoc_insertion_point(class_scope:Ops.AddOp.VectorClock)
    })
  ,
  'DESCRIPTOR' : _ADDOP,
  '__module__' : 'AddOp_pb2'
  # @@protoc_insertion_point(class_scope:Ops.AddOp)
  })
_sym_db.RegisterMessage(AddOp)
_sym_db.RegisterMessage(AddOp.VectorClock)
_sym_db.RegisterMessage(AddOp.VectorClock.VectorEntry)


_ADDOP_VECTORCLOCK_VECTORENTRY._options = None
# @@protoc_insertion_point(module_scope)
